### ISSUE TITLE
Using LoC on Azure DevOps Services  always showing 0 lines of code

### ISSUE THREAD

**Issue by 19ahmed99** [SonarSource/sonar-loc-count#16]
I am trying to run the Azure DevOps script in my organization. The script is able to read the name of the repositories but not the branch names. Also for all the repos the count is 0. 

Here is an example of a repo report: 
 
---------------------------------------------------------------------------------------------------------------------

The maximum lines of code in the < Atlantis.AI.SPO.EditorSurface > project is : <  0 > for the branch : < No >
-----------------------------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------------------------

The maximum lines of code in the < Atlantis.AI.SPO.EditorSurface > project is : <  0 > for the branch : < No >
-----------------------------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------------------------

The maximum lines of code in the < Atlantis.AI.SPO.EditorSurface > project is : <  0 > for the branch : < No >
-----------------------------------------------------------------------------------------------------------------------

I have installed all the installation pre-requisites and I'm running the following command:
./azure_devops_services.sh <my_personal_token> <my_organization>

My personal token has the required permissions Code > Read.

**Comment by emmanuel-colussi-sonarsource** [comment]
Hi @19ahmed99 ,thank you for reporting this issue.The problem has been fixed.

**Comment by 19ahmed99** [comment]
I have pulled the latest version of the repo, and re-ran it again but the issue is still happening. Individual repo reports are not being created, only one for the whole organization and the global.txt. 
Also tried the new command you've added:
./azure_devops_services.sh <token> <organization> <MyProjectName>

But still the count is 0.
